name: docs_molecool
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pydata-sphinx-theme
  - sphinx-design  # pip install sphinx_design
  - sphinx-copybutton

  # make html




    # Pip-only installs
  - pip:
    - -e ../

